version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "testdemochap-master"
s3_bucket = "test1-bucket-chap"
s3_prefix = "testdemochap"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"