AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    product 2 , refactor and faster interaction wilth villa master product
    
Globals:
  Function:
    Timeout: 10
    CodeUri: ./app
    Runtime: python3.8
    Layers:
      - !Ref LambdaLayer
    Environment:
      Variables:
        USERTABLENAME: !Join ['-', ['usertable', 'test', !Ref BRANCH]]
        REGION: !Ref REGION
        BRANCH: !Ref BRANCH
      
      
Parameters: 
  BRANCH: 
    Type: String
    Default: dev-manual
    Description: root branch name
  REGION:
    Type: String
    Default: 'ap-southeast-1'
    
    
    
Resources:
  ######## api gateway #######
  Endpoint:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
        
  ######## functions ######
  HelloWorld:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Join ['-',[ "helloworld", 'function', !Ref BRANCH ]]
      Handler: app.helloworld
      MemorySize: 3008
      Events:
        GetProduct:
          Type: Api 
          Properties:
            Path: /helloworld
            Method: get
            RestApiId: !Ref Endpoint
      
      
      
  ###### dynamodb table #####
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: N 
        - AttributeName: username
          AttributeType: S
        - AttributeName: date
          AttributeType: N
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      TableName: !Join ['-', ['usertable', 'test', !Ref BRANCH]]
      BillingMode: PAY_PER_REQUEST

###### lambdaLayer ######

  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: lambdalayer
      ContentUri: ./layer/package.zip
      CompatibleRuntimes:
        - python3.8

  LayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref LambdaLayer
      Principal: "*"



Outputs:
  ApiId:
    Value: !Ref Endpoint
  Endpoint:
    Value: !Sub 'https://${Endpoint}.execute-api.${REGION}.amazonaws.com/Prod/'
