# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ChangeEmailInput": "changeEmail.ipynb",
         "H": "signUp.ipynb",
         "changeEmail": "changeEmail.ipynb",
         "ChangePasswordInput": "changePassword.ipynb",
         "changePassword": "changePassword.ipynb",
         "USERTABLENAME": "getEnv.ipynb",
         "helloworld": "helloWorld.ipynb",
         "hash_password": "saltHashPassword.ipynb",
         "check_password": "saltHashPassword.ipynb",
         "SignInInput": "signIn.ipynb",
         "signIn": "signIn.ipynb",
         "UserInput": "signUp.ipynb",
         "signUp": "signUp.ipynb",
         "UsernameIndex": "userTable.ipynb",
         "EmailIndex": "userTable.ipynb",
         "UserTable": "userTable.ipynb"}

modules = ["changeEmail.py",
           "changePassword.py",
           "getEnv.py",
           "helloworld.py",
           "saltHashPassword.py",
           "setEnv.py",
           "signIn.py",
           "signUp.py",
           "userTable.py"]

doc_url = "https://thanakijwanavit.github.io/src/"

git_url = "https://github.com/thanakijwanavit/src/tree/main/"

def custom_doc_links(name): return None
