# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/createUser.ipynb (unless otherwise specified).

__all__ = ['createUser']

# Cell
from .userTable import UserTable
from awsSchema.apigateway import Response, Event

# Cell
def createUser(events, *args):

    return True