# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/getEnv.ipynb (unless otherwise specified).

__all__ = ['USERTABLENAME']

# Cell
import os

# Cell
USERTABLENAME = os.environ.get('USERTABLENAME')
USERTABLENAME