# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/signIn.ipynb (unless otherwise specified).

__all__ = ['SignInInput', 'H', 'signIn']

# Cell
from .userTable import UserTable
from awsSchema.apigateway import Response, Event
from copy import deepcopy
from .saltHashPassword import hash_password, check_password
from dataclasses import dataclass
from dataclasses_json import dataclass_json
from beartype import beartype

# Cell
@dataclass_json
@dataclass
class SignInInput:
    username: str
    password: str

    @property
    def passwordHash(self):
        return hash_password(self.password)

    def checkPassword(self):
        passwordHashed = self.passwordHash


# Cell
class H:
    class ParseInputError(Exception): pass
    @staticmethod
    @beartype
    def parseInput(event: dict)->SignInInput:
        try:
            user = Event.parseDataClass(SignInInput, deepcopy(event))
            return user
        except Exception as e:
            raise ParseInputError(e)

    # def

# Cell
def signIn(event, *args):
    # user = H.parseInput(event)
    # userId = user.username
    pass