# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/signIn.ipynb (unless otherwise specified).

__all__ = []

# Cell
from .userTable import UserTable
from awsSchema.apigateway import Response, Event
from copy import deepcopy