# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/signUp.ipynb (unless otherwise specified).

__all__ = ['UserInput', 'H', 'signUp']

# Cell
from .userTable import UserTable
from awsSchema.apigateway import Response, Event
from copy import deepcopy
from beartype import beartype
from uuid import uuid4
from .saltHashPassword import hash_password, check_password
from dataclasses import dataclass
from dataclasses_json import dataclass_json
from time import time
from functools import cached_property
import json

# Cell
@dataclass_json
@dataclass
class UserInput:
    username: str
    password: str
    email: str

    @cached_property
    def passwordHash(self):
        return hash_password(self.password)

    def saveTable(self):
        passwordHashed = self.passwordHash
        userTable = UserTable(
                userId = str(uuid4()),
                username = self.username,
                date = time(),
                passwordHash = passwordHashed,
                email = self.email
            )
        userTable.save()


# Cell
class H:
    class ParseInputError(Exception): pass
    class SavingError(Exception): pass
    class CountUsernameError(Exception): pass
    class UsernameAlreadyExistError(Exception): pass
    class CountEmailError(Exception):pass
    class EmailAlreadyExistError(Exception):pass
    @classmethod
    @beartype
    def parseInput(cls, event:dict)->UserInput:
        try:
            user = Event.parseDataClass(UserInput, deepcopy(event))
            return user
        except Exception as e:
            raise cls.ParseInputError(e)

    @classmethod
    @beartype
    def saveUserMethod(cls, user:UserInput)->bool:
        try:
            usernameExist = UserTable.username_index.count(user.username) > 0
        except Exception as e:
            raise cls.CountUsernameError(e)
        try:
            emailExist = UserTable.email_index.count(user.email) > 0
        except Exception as e:
            raise cls.CountEmailError(e)

        if usernameExist: raise cls.UsernameAlreadyExistError
        if emailExist: raise cls.EmailAlreadyExistError

        try:
            user.saveTable()
            return True
        except Exception as e:
            raise cls.SavingError(e)




# Cell
def signUp(event, *args):
    try:
        user = H.parseInput(event)
        H.saveUserMethod(user)
        return Response.returnSuccess()
    except H.ParseInputError as e:
        return Response.returnError(f'failed to parse input {e}')
    except H.SavingError as e:
        return Response.returnError(f'failed saving user {e}')
    except H.CountUsernameError as e:
        return Response.returnError(f'failed to count number of user {e}')
    except H.UsernameAlreadyExistError as e:
        return Response.returnError(f'username already exist {e}')
    except H.CountEmailError as e:
        return Response.returnError(f'failed to count number of email {e}')
    except H.EmailAlreadyExistError as e:
        return Response.returnError(f'email already exist {e}')
    except Exception as e:
        return Response.returnError(f' unknown error {e}')
