# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/signUp.ipynb (unless otherwise specified).

__all__ = ['UserInput', 'H', 'signUp']

# Cell
from .userTable import UserTable
from awsSchema.apigateway import Response, Event
from copy import deepcopy
from beartype import beartype
from uuid import uuid4
from .saltHashPassword import hash_password, check_password
from dataclasses import dataclass
from dataclasses_json import dataclass_json

# Cell
@dataclass_json
@dataclass
class UserInput:
    username: str
    password: str

    @property
    def passwordHash(self):
        return hash_password(self.password)

    def save(self):
        UserTable(
            userId = self.userId,
            username = self.username,
            date = self.date,
            passwordHash = self.passwordHash
        )


# Cell
class H:
    class ParseInputError(Exception): pass
    @staticmethod
    @beartype
    def parseInput(event:dict)->UserInput:
        try:
            user = Event.parseDataClass(UserInput, deepcopy(event))
            return user
        except Exception as e:
            raise ParseInputError(e)





# Cell
def signUp(events, *args):
    user = H.parseInput(event)
    print(user)
    return Response.returnSuccess()