# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/userTable.ipynb (unless otherwise specified).

__all__ = ['UserTable']

# Cell
from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute, JSONAttribute, NumberAttribute
from .getEnv import USERTABLENAME

# Cell
class UserTable(Model):
    """
    A DynamoDB User
    """
    class Meta:
        table_name = USERTABLENAME
        region = 'ap-southeast-1'
    userId = UnicodeAttribute(hash_key=True)
    username = UnicodeAttribute()
    date = NumberAttribute()
    passwordHash = UnicodeAttribute()

    def toDict(self):
        return {
            'id': self.id,
            'username': self.username,
            'date': self.date,
        }
    def __repr__(self):
        return f'{self.username}\n{self.passwordHash}'