# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/userTable.ipynb (unless otherwise specified).

__all__ = []

# Cell
from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute, JSONAttribute, NumberAttribute
from .getEnv import USERTABLENAME