# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/userTable.ipynb (unless otherwise specified).

__all__ = ['UsernameIndex', 'UserTable']

# Cell
from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute, JSONAttribute, NumberAttribute
from pynamodb.indexes import GlobalSecondaryIndex, AllProjection
from .getEnv import USERTABLENAME

# Cell
class UsernameIndex(GlobalSecondaryIndex):
    """ a global secondary index for username """
    class Meta:
        index_name = 'username'
        read_capacity_units = 2
        write_capacity_units = 1
        projection = AllProjection()

    username = UnicodeAttribute(hash_key=True)

# Cell
class UserTable(Model):
    """
    A DynamoDB User
    """
    class Meta:
        table_name = USERTABLENAME
        region = 'ap-southeast-1'
    userId = UnicodeAttribute(hash_key=True)
    username = UnicodeAttribute()
    date = NumberAttribute()
    passwordHash = UnicodeAttribute()
    email = UnicodeAttribute()
    username_index = UsernameIndex()

    def toDict(self):
        return {
            'id': self.id,
            'username': self.username,
            'date': self.date,
        }
    def __repr__(self):
        return f'{self.username}\n{self.passwordHash}'

